# Generated by Django 4.2 on 2023-04-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdepartment',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('projectDepartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projectdepartment')),
            ],
        ),
    ]
