# Generated by Django 4.2 on 2023-04-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Main Highlights/Achievements', 'verbose_name_plural': 'Main Highlights/Achievements'},
        ),
        migrations.CreateModel(
            name='PlannedScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1000, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project')),
            ],
            options={
                'verbose_name': 'Next Planned Delivery date/Scope',
                'verbose_name_plural': 'Next Planned Delivery date/Scope',
            },
        ),
    ]
