# Generated by Django 4.2 on 2023-04-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_task_options_plannedscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=1000, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project')),
            ],
            options={
                'verbose_name': 'Risks/Blockers',
                'verbose_name_plural': 'Risks/Blockers',
            },
        ),
    ]
