# Generated by Django 4.2 on 2023-04-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_plannedleave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedleave',
            name='date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='plannedleave',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projectmember', unique=True),
        ),
    ]
